export const ErrorCode = {
  REQUIRED: "REQUIRED",
  INVALID_DATE: "INVALID_DATE",
  DATE_RANGE_INVALID: "DATE_RANGE_INVALID",
  INVALID_STATUS: "INVALID_STATUS",

  PROPERTY_VALUE_TOO_LOW: "PROPERTY_VALUE_TOO_LOW",
  AUTO_VALUE_TOO_LOW: "AUTO_VALUE_TOO_LOW",

  DUPLICATE_POLICY_NUMBER: "DUPLICATE_POLICY_NUMBER",
  INVALID_POLICY_TYPE: "INVALID_POLICY_TYPE",
  INVALID_NUMBER: "INVALID_NUMBER",
} as const

export type ErrorCodeT = (typeof ErrorCode)[keyof typeof ErrorCode]
